import { DollarSign, Tag, ClipboardList, Star } from 'lucide-react';
import type { GroceryItem, DashboardKPIs } from '../types';
import KPICard from '../components/kpi/KPICard';
import FatContentDonut from '../components/charts/FatContentDonut';
import ItemTypeBar from '../components/charts/ItemTypeBar';
import EstablishmentTrendLine from '../components/charts/EstablishmentTrendLine';
import OutletSizePie from '../components/charts/OutletSizePie';
import OutletLocationBar from '../components/charts/OutletLocationBar';
import OutletTypeBar from '../components/charts/OutletTypeBar';
import { formatCurrency } from '../components/charts/chartConstants';
import {
  getSalesByFatContent,
  getSalesByItemType,
  getSalesByOutletYear,
  getSalesByOutletSize,
  getSalesByOutletLocation,
  getSalesByOutletType
} from '../lib/dataProcessor';

interface OverviewProps {
  filteredData: GroceryItem[];
  kpis: DashboardKPIs;
}

export default function Overview({ filteredData, kpis }: OverviewProps) {
  // Compute chart datasets from filtered data
  const fatContentData = getSalesByFatContent(filteredData);
  const itemTypeData = getSalesByItemType(filteredData);
  const outletYearData = getSalesByOutletYear(filteredData);
  const outletSizeData = getSalesByOutletSize(filteredData);
  const outletLocationData = getSalesByOutletLocation(filteredData);
  const outletTypeData = getSalesByOutletType(filteredData);

  return (
    <div className="space-y-6">
      {/* KPI Row */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <KPICard
          title="Total Sales"
          value={kpis.totalSales}
          formatter={formatCurrency}
          icon={DollarSign}
          description="Sum of all sales transactions"
        />
        <KPICard
          title="Average Sales"
          value={kpis.averageSales}
          formatter={formatCurrency}
          icon={Tag}
          description="Average order sales value"
        />
        <KPICard
          title="Number of Items"
          value={kpis.numberOfItems}
          formatter={(v) => v.toLocaleString()}
          icon={ClipboardList}
          description="Total active grocery items"
        />
        <KPICard
          title="Average Rating"
          value={kpis.averageRating}
          formatter={(v) => `⭐ ${v.toFixed(2)}`}
          icon={Star}
          description="Customer review rating average"
        />
      </div>

      {/* Empty State */}
      {filteredData.length === 0 && (
        <div className="bg-white border border-slate-100 rounded-2xl p-12 text-center shadow-sm">
          <p className="text-slate-500 font-medium">No data available for the selected filters.</p>
          <p className="text-slate-400 text-xs mt-1">Try resetting or modifying your filters to display analytics.</p>
        </div>
      )}

      {filteredData.length > 0 && (
        /* Charts Grid */
        <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
          {/* Main Sales Trend by Year */}
          <div className="bg-white border border-slate-100 rounded-2xl p-5 shadow-sm xl:col-span-2">
            <h3 className="font-display font-bold text-sm text-slate-800 mb-1">
              Sales Trend by Establishment Year
            </h3>
            <p className="text-[11px] text-slate-500 mb-4">
              Growth overview based on outlet establishment years
            </p>
            <EstablishmentTrendLine data={outletYearData} />
          </div>

          {/* Sales by Fat Content */}
          <div className="bg-white border border-slate-100 rounded-2xl p-5 shadow-sm">
            <h3 className="font-display font-bold text-sm text-slate-800 mb-1">
              Sales by Fat Content
            </h3>
            <p className="text-[11px] text-slate-500 mb-4">
              Distribution of Low Fat vs Regular items
            </p>
            <FatContentDonut data={fatContentData} />
          </div>

          {/* Sales by Item Type (Horizontal Bar) */}
          <div className="bg-white border border-slate-100 rounded-2xl p-5 shadow-sm xl:col-span-2">
            <h3 className="font-display font-bold text-sm text-slate-800 mb-1">
              Sales by Item Type
            </h3>
            <p className="text-[11px] text-slate-500 mb-4">
              Revenue generated by various grocery item categories
            </p>
            <ItemTypeBar data={itemTypeData} limit={10} />
          </div>

          {/* Sales by Outlet Size */}
          <div className="bg-white border border-slate-100 rounded-2xl p-5 shadow-sm">
            <h3 className="font-display font-bold text-sm text-slate-800 mb-1">
              Sales by Outlet Size
            </h3>
            <p className="text-[11px] text-slate-500 mb-4">
              Performance breakdown by size class (Small, Medium, High)
            </p>
            <OutletSizePie data={outletSizeData} />
          </div>

          {/* Sales by Outlet Location */}
          <div className="bg-white border border-slate-100 rounded-2xl p-5 shadow-sm">
            <h3 className="font-display font-bold text-sm text-slate-800 mb-1">
              Sales by Outlet Location
            </h3>
            <p className="text-[11px] text-slate-500 mb-4">
              Revenue distribution across Tier 1, 2, and 3 locations
            </p>
            <OutletLocationBar data={outletLocationData} />
          </div>

          {/* Sales by Outlet Type */}
          <div className="bg-white border border-slate-100 rounded-2xl p-5 shadow-sm xl:col-span-2">
            <h3 className="font-display font-bold text-sm text-slate-800 mb-1">
              Sales by Outlet Type
            </h3>
            <p className="text-[11px] text-slate-500 mb-4">
              Performance comparison across formats (Grocery Store, Supermarkets)
            </p>
            <OutletTypeBar data={outletTypeData} />
          </div>
        </div>
      )}
    </div>
  );
}
